version: '3.8'

services:
  omada-mongodb:
    image: mongo:4.4
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  omada-controller:
    image: ubuntu:20.04  # Using a basic Ubuntu image
    restart: always
    depends_on:
      - omada-mongodb
    volumes:
      - ./Omada:/opt/tplink/EAPController  # Local directory to store the .deb file
    environment:
      - MONGODB_URI=mongodb://omada-mongodb:27017
    ports:
      - "8088:8088"
      - "8043:8043"
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y wget gdebi-core && 
      wget https://static.tp-link.com/upload/software/2024/202407/20240710/Omada_SDN_Controller_v5.14.26.1_linux_x64.deb &&
      gdebi -n Omada_SDN_Controller_v5.14.26.1_linux_x64.deb &&
      rm Omada_SDN_Controller_v5.14.26.1_linux_x64.deb &&
      java -jar /opt/tplink/EAPController/lib/Omada.jar
      "

volumes:
  mongodb_data:
